export const FETCH_DATA_MOVIE_REQUEST = 'FETCH_DATA_MOVIE_REQUEST';
export const FETCH_DATA_MOVIE = 'FETCH_DATA_MOVIE';
export const FETCH_DATA_USERS = 'FETCH_DATA_USERS';
export const FETCH_DATA_ADMIN = 'FETCH_DATA_ADMIN';

export const SAVE_ACCOUNT = 'SAVE_ACCOUNT';

export const REGISTER_USER = 'REGISTER_USER';


export const SEARCH_MOVIE_REQUEST = 'SEARCH_MOVIE_REQUEST';
export const SEARCH_MOVIE = 'SEARCH_MOVIE';