export const FETCH_DATA_MOVIE_REQUEST = 'FETCH_DATA_MOVIE_REQUEST';
export const FETCH_DATA_MOVIE = 'FETCH_DATA_MOVIE';
export const FETCH_DATA_USERS = 'FETCH_DATA_USERS';
export const FETCH_DATA_ADMIN = 'FETCH_DATA_ADMIN';
export const FETCH_DATA_ACCOUNT = 'FETCH_DATA_ACCOUNT';
export const FETCH_DATA_SUPPORT = 'FETCH_DATA_SUPPORT';

export const SAVE_ACCOUNT = 'SAVE_ACCOUNT';

export const REGISTER_USER = 'REGISTER_USER';

export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';

export const SEARCH_MOVIE = 'SEARCH_MOVIE';

export const FETCH_SHOWTIMES = 'FETCH_SHOWTIMES';

export const RECEIVE_MOVIE_CHOOSING = 'RECEIVE_MOVIE_CHOOSING';

export const SHOW_INFORMATION_MOVIE = 'SHOW_INFORMATION_MOVIE';

export const RATING_ITEM_MOVIE = 'RATING_ITEM_MOVIE';

export const UPDATE_USER = 'UPDATE_USER';

export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';

export const FETCH_DATA_TICKETS_REQUEST = 'FETCH_DATA_TICKETS_REQUEST';
export const FETCH_DATA_TICKETS = 'FETCH_DATA_TICKETS';
export const FETCH_DATA_FOOD = 'FETCH_DATA_FOOD';